site_name: CyberInsecurities
site_url: https://garysuyemoto.com/blog/
theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
    - content.code.annotate
  icon:
    logo: octicons/command-palette-24
  palette:
    scheme: slate
    primary: teal
    accent: yellow
  font:
    text: Roboto
plugins:
  - meta
  - blog:
      blog_dir: . 
  - search
  - tags
nav:
  - index.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

